### PR TITLE
Version bump, small refactor, removed some deprecated stuff

### PR DESCRIPTION
**Pull request by karatekaneen**
Did some updates and rewrote a little bit when i read the code to understand it and thought I might as well contribute them.

Thank you for this package

### CODE REVIEW

**Review by benevolent0505 — APPROVED** [review]
Thank you for your contribution!

**Comment by benevolent0505** [comment]
@karatekaneen I have a question. Why is the GitHub account that submitted the Pull Request different from the GitHub account of the commit author?

**Comment by karatekaneen** [comment]
@benevolent0505 Ah, it's because I did the changes on my work laptop but this is my private account so the "real" author account does not exist on github

**Comment by benevolent0505** [comment]
@karatekaneen Understood. If you contribute again, I'd appreciate it if the account for committing and submitting the Pull Request could be the same. Thank you!

**Pull request merged**
